version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
