version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=my_secret_key

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URI=postgres://user:password@localhost/db

  transaction-processing:
    build:
      context: ./transaction-processing
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - BROKER_URL=amqp://guest:guest@localhost

  account-management:
    build:
      context: ./account-management
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URI=postgres://user:password@localhost/db
