---
- name: Configure Pi Network web
  become: yes

  tasks:
  - name: Configure Pi Network web
    template:
      src: templates/pi-network-web.conf.j2
      dest: /etc/nginx/sites-available/pi-network-web
      mode: '0644'
    notify: restart nginx

  - name: Start Pi Network web
    service:
      name: pi-network-web
      state: started
      enabled: yes
