apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-network
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pi-network
  template:
    metadata:
      labels:
        app: pi-network
    spec:
      containers:
      - name: pi-network
        image: <your-pi-network-image>
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
