apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pi-network-rolebinding
  namespace: pi-network
roleRef:
  name: pi-network-role
  kind: Role
subjects:
  - kind: ServiceAccount
    name: pi-network
    namespace: pi-network
