version: '3'

services:
  pi-network:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PI_NETWORK_PORT=8080
      - PI_NETWORK_DB_HOST=db
      - PI_NETWORK_DB_PORT=5432
      - PI_NETWORK_DB_USER=pi_network
      - PI_NETWORK_DB_PASSWORD=pi_network_password
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=pi_network
      - POSTGRES_PASSWORD=pi_network_password
      - POSTGRES_DB=pi_network
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
