apiVersion: v1
kind: Service
metadata:
  name: pi-network
spec:
  selector:
    app: pi-network
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 10.0.0.100
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
