apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-nexus-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pi-nexus-api
  template:
    metadata:
      labels:
        app: pi-nexus-api
    spec:
      containers:
      - name: pi-nexus-api
        image: pi-nexus-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
