# docker-compose.yml
version: '3'
services:
did_based_autonomous_banking_api:
    build: .
    environment:
      - API_KEY=your_api_key
      - API_SECRET=your_api_secret
    ports:
      - "8093:8093"
